---

- hosts: all
  tasks:
    - name: pull docker image from docker hub
      community.docker.docker_image:
        name: ragesh18/thmho-lidar-node:docker
        source: pull

    - name: run docker container with pulled image
      community.docker.docker_container:
        name: testnode
        image: ragesh18/thmho-lidar-node:docker
