---

- hosts: all
  tasks:

  - name: pull docker image community
    community.docker.docker_image:
      name: ragesh18/thmho-lidar-node:main
      source: pull
      force_source: yes

  - name: prune unnecesary docker images
    community.docker.docker_prune:
      images: yes

      # - name: run docker container with pulled image
      #   community.docker.docker_container:
      #     name: testnode
      #     image: ragesh18/thmho-lidar-node:main


