---

- hosts: all
  tasks:

  - name: pull desired repo
    ansible.builtin.git:
      repo: git@github.com:ipa-rar-sg/THMHO_dashboard.git
      dest: /home/ganbatte/THMHO
      single_branch: yes
      version: sparsenosql

  - name: Install docker sdk for python
    pip:
      name: docker

  - name: run docker container
    community.docker.docker_container:
      name: ansitest
      image: python:3.9-slim
