---

- hosts: all
  tasks:

  - name: Install docker sdk for python
    pip:
      name: docker

  - name: pull docker image community
    community.docker.docker_image:
      name: ragesh18/thmho-lidar-node:main
      source: pull

  - name: run docker container with pulled image
    community.docker.docker_container:
      name: testnode
      image: ragesh18/thmho-lidar-node:main

  - name: pull desired repo
    ansible.builtin.git:
      repo: git@github.com:ipa-rar-sg/THMHO_dashboard.git
      dest: /dir/dir2
      single_branch: yes
      version: sparsenosql


